Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20200817130116_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

Installation of devise is ok :)

---

config/initializers/devise.rb

Create the model for the Booking with the references with the id and the user

Add model booking

---

app/models/booking.rb
db/migrate/20200817140640_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

create the model with the references

add_model_booking

---

app/controllers/offers_controller.rb

offers methods index/create

---

app/views/offers/index.html.erb

index-view

---

app/controllers/offers_controller.rb
app/views/offers/show.html.erb

offers show

---

app/views/layouts/application.html.erb

need to connect buttons now :)

adding button connect/disconnect

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb

Button disconnect is working, I added some padding on the navbar, but now we need to think about the menu to know what action to purpose to user

Editing navbar with disconnect button

---

app/models/booking.rb
app/models/offer.rb
app/models/user.rb

model-modif

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_index.scss
app/models/offer.rb
app/views/layouts/application.html.erb
app/views/offers/index.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20200817161833_add_image_to_offers.rb
db/migrate/20200817162949_add_image_to_offers.rb
db/migrate/20200818090745_create_active_storage_tables.active_storage.rb
db/schema.rb
db/seeds.rb

Front image

---

app/controllers/offers_controller.rb
app/views/offers/index.html.erb
app/views/offers/new.html.erb
app/views/offers/show.html.erb

Creation of the definition Destroy + path + show

Creation of the definition Destroy for offer, resolving and creation path

---

.gitignore

add mad seeds

---

app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

add avatar picture

---

app/models/offer.rb
app/views/offers/_form.html.erb

add picture to your offer

---

app/controllers/offers_controller.rb
app/views/offers/index.html.erb

reparation controller

---

app/javascript/channels/index.js
app/views/layouts/application.html.erb
app/views/offers/_form.html.erb

everything works, it was a problem with typewriter plug-in

navbar fixed

---

app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/offers_controller.rb
app/views/offers/show.html.erb
config/routes.rb
test/controllers/bookings_controller_test.rb

Create the definition to create a Booking for a offer and the view

Booking setup

---

app/controllers/offers_controller.rb
app/views/offers/index.html.erb

reparation ajouter photo sur offer

reparation

---

app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
config/environments/production.rb

2 files more than application now : footer and navbar

Clean our files

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/users_controller.rb
app/views/shared/_navbar.html.erb
app/views/users/dashboard.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

Profile page with current id of the user and show

Profile page

---

app/views/users/show.html.erb

Merge the profil page 2 with update for the path

merge the profil page

---

app/assets/stylesheets/pages/_index.scss
app/views/offers/show.html.erb

Front show

---

app/views/shared/_navbar.html.erb

Add a another photo profil by default and fixed the demension

resolving problem photo by default

---

Gemfile
Gemfile.lock
app/controllers/offers_controller.rb
app/models/offer.rb
app/views/pages/home.html.erb
config/routes.rb

Create the gem to research a word il relation with an offer

push pg-search-gem

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show-booking.scss
app/views/bookings/show.html.erb

show booking html

---

app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/views/offers/_form.html.erb

address input

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Begining of the Creation of the navabar

begining of the search bar design
